# -*- mode: ruby -*-
# vi: set ft=ruby :

# VARIABLES
BOX_IMAGE = "debian/bookworm64"
PROVIDER = "virtualbox"
NUM_CPUS = 2
MEMORIA_RAM = 2048
NOM_MAQUINA = "pj9f4a87-grup06"
HOSTNAME = "pj9f4a87-grup06.fjeclot.net"

# Camins de carpetes compartides


# CONFIGURACIÓ DE LA MÀQUINA
Vagrant.configure("2") do |config|

  # BOX
  config.vm.box = BOX_IMAGE

  # CONFIGURACIÓ ESPECÍFICA DEL PROVIDER
  config.vm.provider PROVIDER do |provider|
    provider.name = NOM_MAQUINA
    provider.memory = MEMORIA_RAM
    provider.cpus = NUM_CPUS
    provider.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end

  # CONFIGURACIÓ GENERAL
  config.vm.hostname = HOSTNAME
  config.vm.synced_folder "../app1", "/home/vagrant/aplicacions/app1"
  config.vm.synced_folder "../app2", "/home/vagrant/aplicacions/app2"
  config.vm.synced_folder "../documentacio", "/home/vagrant/documentacio"
  config.vm.network "public_network"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get -y update
    sudo apt-get -y install net-tools whois aptitude git zip unzip

    sudo apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    sudo apt-get -y update
    sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose

    # Configuració de permisos per a l'usuari vagrant
    sudo gpasswd -a vagrant docker
  SHELL
end
