services:
  app:
    image: httpd:latest
    container_name: starship-container
    volumes:
      - ./codi/starship-sorades-13k:/usr/local/apache2/htdocs
    expose:
      - "80"
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


