services:
  app:
    image: httpd:latest
    volumes:
      - ./codi/starship-sorades-13k:/usr/local/apache2/htdocs
    expose:
      - "80"
  
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf